// Loader for the bundled FFXIV game data (generated by scripts/gen-gamedata.mjs into
// public/assets/gamedata). Replaces the plugin's live Lumina sheet reads. Each dataset is fetched
// once and memoised; callers tolerate failure (the data is optional flavour, like the C# screens
// which degrade to "(unavailable)" when a sheet can't be read).

export interface Territory {
    id: number;
    name: string;
}

const BASE = `${import.meta.env.BASE_URL}assets/gamedata`;

let territoriesPromise: Promise<Territory[]> | null = null;

/** Named territories for the favourite-location picker (sorted, distinct by name). */
export function loadTerritories(): Promise<Territory[]> {
    territoriesPromise ??= fetch(`${BASE}/territories.json`)
        .then((r) => (r.ok ? (r.json() as Promise<Territory[]>) : []))
        .catch(() => []);
    return territoriesPromise;
}

/** URL of the job's class icon, or null for Job.None / jobs without a bundled icon. */
export function jobIconUrl(job: number): string | null {
    return job > 0 ? `${BASE}/jobs/${job}.png` : null;
}
